<?php
/*
 * Copyright (c) 2020. Victor Barcellos Lopes
 */
/** @var Magento\Framework\View\Element\Template $block */
?>

<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */echo __('* Required Fields') ?>">
    <legend class="legend">
        <span><?php /* @escapeNotVerified */echo __('Pet Information') ?></span>
    </legend>
    <br>
    <div class="field pet_name required">
        <label class="label" for="pet_kind">
            <span><?= $block->escapeHtml(__('Pet Kind')) ?></span>
        </label>
        <select id="pet_kind" name="pet_kind" title="Pet Kind" class="control validate-select" data-validate="{required:true}">
<!--            --><?php //$options = $block->getPetKindOptions(); ?>
<!--            --><?php //foreach ($options as $option) : ?>
            <option value="" selected="selected"'></option>
            <option value="4"'>Dog</option>
<!--                <option value="" selected="selected"'>--><?//= $block->escapeHtml(__($option->getLabel())) ?><!--</option>-->
<!--            --><?php //endforeach;?>
        </select>
    </div>
    <div class="field pet_name required">
        <label class="label" for="pet_name">
            <span><?= $block->escapeHtml(__('Pet Name')) ?></span>
        </label>
        <div class="control">
            <input type="text" name="pet_name" id="pet_kind" title="<?php /* @escapeNotVerified */echo __('Pet Name') ?>" class="input-text" data-validate="{required:true}" autocomplete="off">
        </div>
    </div>
</fieldset>
