<?php
/**
 * Copyright (c) 2020. Victor Barcellos Lopes
 */

declare(strict_types=1);

namespace Webjump\CliCommandTopic\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class HelloWorld
 * @package Webjump\CliCommandTopic\Console\Command
 */
class HelloWorld extends Command
{
    /**
     * @inheritDoc
     */
    protected function configure(): void
    {
        $this->setName('hello:world');
        $this->setDescription('Command created for the academy\'s backend course nº 2');
        $this->addArgument(
            'text',
            InputOption::VALUE_REQUIRED,
            'Text'
        );
        parent::configure(); // TODO: Change the autogenerated stub
    }

    /**
     * Execute the command
     *
     * @param InputInterface $input
     * @param OutputInterface $output
     *
     * @return void
     */
    protected function execute(InputInterface $input, OutputInterface $output): void
    {
        $output->writeln('<info>Hello World: ' . $input->getArgument('text') . ' </info>');
    }
}
